name: Java CI

on: [push]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Build (jlink)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jlink

      - name: Build (jpackage)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jpackage
